language: java
sudo: false
jdk: openjdk12
dist: trusty

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "olszewskimichal-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      - develop
script:
  - sonar-scanner

jobs:
  include:
    - stage: test
      script:
        - mvn test -B
      after_success:
        - mvn sonar:sonar -Dsonar.coverage.exclusions=**/pl/michal/olszewski/rssaggregator/config/** -Dsonar.coverage.jacoco.xmlReportPaths=./model/target/site/jacoco-aggregate/jacoco.xml,./modelPersistence/target/site/jacoco-aggregate/jacoco.xml,./items/target/site/jacoco-aggregate/jacoco.xml,./search/target/site/jacoco-aggregate/jacoco.xml,./blogs/target/site/jacoco-aggregate/jacoco.xml,./application/target/site/jacoco-aggregate/jacoco.xml,./target/site/jacoco-aggregate/jacoco.xml,./cache/target/site/jacoco-aggregate/jacoco.xml
        - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - olsz72@o2.pl
    on_success: change
    on_failure: always