language: java
sudo: false
jdk: openjdk12
dist: trusty

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.sonar/cache

addons:
  sonarcloud:
    organization: "olszewskimichal-github"
    token:
      secure: ${SONAR_TOKEN}
    branches:
      - master
      - develop
script:
  - sonar-scanner

jobs:
  include:
    - stage: test
      script:
        - mvn test sonar:sonar -Dsonar.coverage.exclusions=**/pl/michal/olszewski/rssaggregator/config/** -B
      after_success:
        - bash <(curl -s https://codecov.io/bash) -s "target/"
notifications:
  email:
    recipients:
      - olsz72@o2.pl
    on_success: change
    on_failure: always